### PR TITLE
Create alecumadalin32.yaml

### PR DESCRIPTION
**Pull request by AlecuMadalin32**

### CODE REVIEW

**Comment by nukeop** [comment]
I can't find your name here, can you tell us which signature is yours? https://rms-open-letter.github.io/

**Comment by shenlebantongying** [comment]
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/4208

**Comment by Aspie96** [comment]
> [rms-support-letter/rms-support-letter.github.io#4208](https://github.com/rms-support-letter/rms-support-letter.github.io/pull/4208)

They must have signed the Open Letter not the support one

**Comment by AlecuMadalin32** [comment]
Cancel / delete this commit, i assigned this letter by accident. 
i apologize for this mistake

**Comment by Aspie96** [comment]
You signed by mistake a letter for those who signed by mistake

**Pull request closed without merging**
