### PR TITLE
Remove my signature

### PR DESCRIPTION
**Pull request by ghost**
I would like my signature removed please.

### CODE REVIEW

**Comment by ghost** [comment]
And please ensure the name doesn't stay in _data/signed

**Comment by nukeop** [comment]
This is a repo for removing signatures from https://rms-open-letter.github.io/, is this what you intended to do?

**Comment by ghost** [comment]
My apologies I thought it was to remove from the support letter. I don't think that would be possible, would it?

**Comment by nukeop** [comment]
That repository is archived now.

**Comment by ghost** [comment]
Ah, my apologies. In that case feel free to delete this pull request.

**Pull request closed without merging**
